### ISSUE TITLE
Displaying alerts with actions?

### ISSUE THREAD

**Issue by woj-tek** [h4llow3En/mac-notification-sys#31]
Is there a plan to be able to show Alerts (instead of plain notifications): https://developer.apple.com/documentation/uikit/uialertcontroller ?

**Comment by h4llow3En** [comment]
I don't think, that UIKit is suitable for this project

> Construct and manage a graphical, event-driven user interface for your iOS or tvOS app

This description of UIKit states that it is designed for
1. graphical interfaces
2. iOS oder tvOS

Since notifications can be triggered using cli only this crate will use these.

NSUserNotifications are deprecated but switching to the newer UN* API (#10).
Unfortunately you have to be a signed application to access that API. (This seems to be the same if we would like to use the ui kit)
